#!/bin/bash

function usage
{
  echo "description:"
  echo "generate_images will generate all of the required images for the assignment"
  echo "and output them in a new folder"
  echo "usage:"
  echo "generate_images -f path/to/file.bmp\n"
  echo "options:"
  echo "-f : Provide a file path to source image"
  echo "-h : Display usage" 
}

case $1 in
  -f | --file )
    shift
    file=$1
    ;;
  -h | --help )
    usage
    exit
    ;;
  * )
    usage
    exit 1
    ;;
esac

if [ "$file" != "" ]; then
  fname="${file##./}"
  fname="${fname%.*}"
else
  echo "error: must provide filename"
  exit 1;
fi

if [ -f $file ]; then
  echo "Generating images . . ."
  mkdir ${fname}
  for flag in -c -g -p -b -r90 -r180 -r270 -v -h -d1 -d2 -grow -shrink 
  do
    echo "running with flag: ${flag}"
    ./bitmap $flag "$file" "${fname}/${fname}${flag}.bmp"
  done
  echo "Finished generating images!"
  exit 0
else
  echo "error: file does not exist"
  exit 1
fi
